[tool.poetry]
name = "strawberry"
version = "0.1.0"
description = "A library for creating GraphQL APIs"
authors = ["Patrick Arminio <patrick.arminio@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
graphql-core-next = "^1.0"

[tool.poetry.dev-dependencies]
pytest = "^4.2"
pdbpp = "^0.9.5"
bpython = "^0.17.1"
pytest-emoji = "^0.2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
